<?php declare(strict_types=1);
# Generated by the OpenSwoole compiler. DO NOT EDIT!
# source: helloworld.proto

namespace Helloworld;

use OpenSwoole\GRPC;

class StreamClient extends \OpenSwoole\GRPC\BaseStub
{


	/**
    * @param HelloRequest $request
    * @return HelloReply
    *
    * @throws \OpenSwooleGRPC\Exception\InvokeException
    */
    public function FetchResponse(HelloRequest $request, $metadata = []): HelloReply {
    	return $this->_serverStreamRequest('/helloworld.Stream/FetchResponse',
        $request,
        ['\Helloworld\HelloReply', 'decode'],
        $metadata); 
    }

	public function getNext(): object {
	    return $this->_getData();
	}
}
