<?php declare(strict_types=1);
# Generated by the OpenSwoole compiler. DO NOT EDIT!
# source: helloworld.proto

namespace Helloworld;

use OpenSwoole\GRPC;

interface StreamInterface extends GRPC\ServiceInterface
{
    public const NAME = "/helloworld.Stream";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HelloRequest $request
    * @return HelloReply
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function FetchResponse(GRPC\ContextInterface $ctx, HelloRequest $request): HelloReply;
}
